### ISSUE TITLE
OUTPUT

### ISSUE THREAD

**Issue by jrue00** [KennyNapaluch/nfl-spread-picker#1]
when I am running this. it gives an output that looks like this (Predicted winner: WSH (57.79) over CHI (42.21). Spread: -6.0) Is this a prediction that WSH will win the game out right or cover the spread?

**Comment by KennyNapaluch** [comment]
This program is designed to predict NFL game outcomes and adjust Elo ratings based on actual game results. It also considers point spreads and odds information to make predictions for upcoming games. The output shows the teams likelihood to cover the spread. This program is a project that is in its early stages, so results might not be reliable.
